const { readFileSync, writeFileSync } = require("node:fs");
const { resolve } = require("node:path");
const { cssVariables } = require("../tokens.cjs");

const outputPath = resolve(__dirname, "..", "tokens.css");
const output = `/* Generated by scripts/generate-css.cjs from tokens.cjs. Do not edit. */
:root {
${Object.entries(cssVariables)
  .map(([name, value]) => `  ${name}: ${value};`)
  .join("\n")}
}
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== output) {
    console.error("tokens.css is stale. Run: pnpm --filter @vibaar/design-tokens generate");
    process.exit(1);
  }
} else {
  writeFileSync(outputPath, output);
}
