-- RW1 / money-safety: exactly ONE signup bonus per user, enforced by the database.
--
-- CreditSignupBonus checks for an existing signup_bonus entry and then inserts.
-- Inside one transaction that stops a RETRY, but under READ COMMITTED two
-- concurrent signups for the same user can both read zero rows and both insert,
-- double-granting the bonus. Application-level check-then-write cannot fix that;
-- a unique index can.
--
-- Partial index (not a table constraint) because uniqueness applies only to the
-- signup_bonus type — a user legitimately has many other credit entries.
--
-- Plain CREATE UNIQUE INDEX, not CONCURRENTLY: the boot runner wraps each file in
-- a transaction, and CONCURRENTLY cannot run inside one. The table is small at
-- launch scale, so the brief lock is fine.
--
-- ON PRE-EXISTING DUPLICATES — deliberately NOT auto-repaired.
--
-- An earlier draft of this migration DELETEd duplicate signup_bonus rows before
-- creating the index. That was wrong: the duplicate ledger rows have already been
-- added to users.shopping_credit, so deleting them silently breaks the
-- ledger-equals-balance invariant and leaves the user holding credit with no
-- audit trail explaining it. Worse, it would do so quietly, on boot.
--
-- So this migration is now purely additive. If duplicates exist, CREATE UNIQUE
-- INDEX fails on its own with a precise Postgres error naming the duplicated
-- user_id, the boot runner halts the service (by design — see versioned.go), and
-- a human reconciles before anything serves traffic. A money invariant should
-- fail loudly, not self-heal.
--
-- To check BEFORE deploying:
--
--   SELECT user_id, COUNT(*), SUM(amount)
--   FROM credit_entries WHERE type = 'signup_bonus'
--   GROUP BY user_id HAVING COUNT(*) > 1;
--
-- If that returns rows, decide per user whether the excess credit was spent
-- before removing ledger rows, and adjust users.shopping_credit to match.

CREATE UNIQUE INDEX IF NOT EXISTS idx_credit_entries_one_signup_bonus_per_user
    ON credit_entries (user_id)
    WHERE type = 'signup_bonus';
